Repository UN-OCHA/hpc-api-core, pull requests merged in 2021-11, with the labels that each got.

#28 🎨 Migrate all ID types to hpc-api-core
  src/db/models/blueprint.ts
  src/db/models/budgetSegment.ts
  src/db/models/budgetSegmentBreakdown.ts
  src/db/models/budgetSegmentBreakdownEntity.ts
  src/db/models/category.ts
  src/db/models/conditionField.ts
  src/db/models/emergency.ts
  src/db/models/externalData.ts
  src/db/models/externalReference.ts
  src/db/models/fileAssetEntity.ts
  src/db/models/flow.ts
  src/db/models/globalCuster.ts
  src/db/models/globalCusterAssociation.ts
  src/db/models/governingEntityVersion.ts
  src/db/models/iatiActivity.ts
  src/db/models/iatiRecipientCountry.ts
  src/db/models/iatiTransaction.ts
  src/db/models/job.ts
  src/db/models/location.ts
  src/db/models/measurement.ts
  src/db/models/measurementVersion.ts
  src/db/models/organization.ts
  src/db/models/participantCountry.ts
  src/db/models/participantOrganization.ts
  src/db/models/planEntity.ts
  src/db/models/planEntityVersion.ts
  src/db/models/planLocation.ts
  src/db/models/planReportingPeriod.ts
  src/db/models/planVersion.ts
  src/db/models/planYear.ts
  src/db/models/procedureEntityPrototype.ts
  src/db/models/procedureSection.ts
  src/db/models/projectContact.ts
  src/db/models/projectVersionHistory.ts
  src/db/models/tag.ts
  src/db/models/task.ts
  src/db/models/usageYear.ts
  src/db/models/workflowRole.ts
  src/db/models/workflowStatusOptionStep.ts
Labels: ready for review

#30 Define models needed for HPC-7904
  .gitignore
  package.json
  src/db/index.ts
  src/db/models/attachmentPrototype.ts
  src/db/models/entityPrototype.ts
  src/db/models/governingEntityVersion.ts
  src/db/models/location.ts
  src/db/models/planEntityVersion.ts
  src/db/models/planVersion.ts
  src/db/models/planYear.ts
  src/db/models/project.ts
  src/db/models/projectVersionAttachment.ts
  src/db/models/usageYear.ts
  src/db/models/workflowStatusOption.ts
  src/db/util/datatypes.ts
  src/util/async.ts
  yarn.lock
Labels: ready for review

#25 Add permissions for cloning projects
  src/auth/permissions.ts
  src/auth/roles.ts
Labels: ready for review

#31 🐛 Correct properties for attachment model
  package.json
  src/db/models/attachment.ts
  src/db/models/planVersion.ts
Labels: ready for review

#34 Specify `@types/lodash` and `@types/node-fetch` as regular dependencies
  package.json
Labels: ready for review

#32 ✨ HPC-8205: Remaining changes neccesary for HPC-8205
  src/db/models/attachmentPrototype.ts
  src/db/models/attachmentVersion.ts
  src/db/models/json/attachment.ts
  src/db/models/json/indicatorsAndCaseloads.ts
  src/db/util/errors.ts
  src/db/util/id-model.ts
  src/db/util/legacy-versioned-model.ts
  src/db/util/raw-model.ts
  src/db/util/sequelize-model.ts
  src/db/util/validation.ts
  src/db/util/versioned-model.ts
  src/util/index.ts
  src/util/io-ts.ts
Labels: ready for review

#33 ♻️ Move HPC-8205 functions into hpc-api-core
  src/lib/context.ts
  src/lib/data/attachments.ts
  src/lib/data/governingEntities.ts
  src/lib/data/planEntities.ts
  src/lib/data/projects.ts
Labels: ready for merge

#35 Add projectVersionField to v4 models
  src/db/index.ts
  src/db/models/projectVersionField.ts
Labels: ready for review

#42 Define models needed for HPC-8163
  package.json
  src/db/index.ts
  src/db/models/projectContact.ts
  src/db/models/projectVersionOrganization.ts
Labels: ready for review

#41 ✨ HPC-8260: Required changes to address HPC-8260
  src/db/index.ts
  src/db/models/organization.ts
  src/lib/data/projects.ts
Labels: needs rebase

#40 HPC-8203: Allow plan leads to make the plan visible in PM
  src/auth/permissions.ts
  src/auth/roles.ts
Labels: ready for review

#39 ✨ HPC-8206: Required changes to extend gap analysis endpoint with disaggregated data
  src/db/models/json/indicatorsAndCaseloads.ts
  src/db/models/planEntityVersion.ts
  src/db/models/projectVersionAttachment.ts
  src/lib/data/planEntities.ts
  src/util/io-ts.ts
Labels: ready for review

#43 Accept `null` for `optional` user data
  src/db/util/model-definition.ts
Labels: ready for review

#45 🔖 Bump version to `v0.5.0`
  package.json
Labels: ready for review

#47 Add createMany function in db library
  src/db/util/raw-model.ts
Labels: ready for review

#36 🎨 Use new db util functions for consistent errors
  src/db/fetching.ts
  src/db/util/validation.ts
  src/db/util/versioned-model.ts
  src/lib/data/attachments.ts
  src/lib/data/governingEntities.ts
  src/lib/data/planEntities.ts
  src/lib/data/projects.ts
  src/util/index.ts
Labels: ready for merge

#48 Define `conditionField` and related models
  package.json
  src/db/index.ts
  src/db/models/conditionField.ts
  src/db/models/conditionFieldReliesOn.ts
  src/db/models/conditionFieldType.ts
Labels: ready for review

#51 Reduce precision of knex updatedAt and createdAt to 3
  src/db/util/sequelize-model.ts
Labels: ready for review

#52 🔖 Bump version to `v0.7.0`
  package.json
Labels: ready for merge

#53 HPC-8202: Restrict deleting projects to administrators in API
  package.json
  src/auth/permissions.ts
Labels: ready for review

#54 Add ability to get current and latest versions of project plans
  package.json
  src/lib/data/projects.ts
Labels: ready for review

#55 Expose `DISAGGREGATED_LOCATIONS` codec
  package.json
  src/db/models/json/indicatorsAndCaseloads.ts
Labels: needs minor changes

#56 ⬆️ Update `@unocha/hpc-repo-tools` to `v0.2.2`
  package.json
  yarn.lock
Labels: ready for review

#50 ✨ Introduce getGoverningEntityIDsForProjects
  src/lib/data/projects.ts
Labels: ready for merge

#58 Define budget segment models
  package.json
  src/db/index.ts
  src/db/models/budgetSegment.ts
  src/db/models/budgetSegmentBreakdown.ts
  src/db/models/budgetSegmentBreakdownEntity.ts
Labels: ready for review

#61 🔖 Bump version to `v0.9.0`
  package.json
Labels: ready for merge
