Repository UN-OCHA/hpc-api-core, pull requests merged in 2022-03, with the labels that each got.

#76 HPC-8305: Disable softdelete for the table planYear
  package.json
  src/db/models/planYear.ts
Labels: ready for review

#85 Introduce cloning permission for plan leads
  src/auth/permissions.ts
  src/auth/roles.ts
  src/db/models/planYear.ts
Labels: ready for merge

#84 Add `creatorParticipantId` column to `disaggregationModel` table
  package.json
  src/db/models/disaggregationModel.ts
Labels: ready for merge

#88 HPC-8409:Temporary fix to facilitate Anonymisation of Orgs
  package.json
  src/db/models/flowObjectType.ts
Labels: needs minor changes
