Repository UN-OCHA/hpc-api-core, pull requests merged in 2024-09, with the labels that each got.

#156 Update dependencies & enable Dependabot version updates
  .git-blame-ignore-revs
  .github/dependabot.yml
  .husky/pre-commit
  package.json
  src/db/fetching.ts
  src/db/models/authTarget.ts
  src/db/util/id-model.ts
  src/db/util/model-definition.ts
  src/db/util/raw-model.ts
  src/db/util/types.ts
  src/lib/data/projects.ts
  src/util/index.ts
  tsconfig.json
  yarn.lock
Labels: ready for merge, dependencies

#161 HPC-9504: Upgrade to ESLint 9
  .eslintignore
  .eslintrc.js
  eslint.config.js
  package.json
  src/lib/data/attachments.ts
  tests/utils/connection.ts
  yarn.lock
Labels: ready for merge, dependencies

#146 HPC-9489: Creation of new datapoints attached to plans
  src/db/index.ts
  src/db/models/categoryGroup.ts
  src/db/models/plan.ts
  src/db/models/planVersion.ts
  src/db/models/planVersionOrganization.ts
Labels: ready for merge

#162 🔖 Bump version to `v10.1.0`
  package.json
Labels: ready for review
