Repository UN-OCHA/hpc-api-core, pull requests merged in 2024-08, with the labels that each got.

#152 HPC-8569: Add `count` function and `distinct` option to models library
  src/db/util/raw-model.ts
Labels: needs unit tests

#153 HPC-8569: Export 'FieldsOfModel'
  src/db/util/types.ts
Labels: ready for review

#154 HPC-8383: Upgrade knex to latest version
  package.json
  src/auth/index.ts
  src/db/deletion/project.ts
  src/db/index.ts
  src/db/models/authGrant.ts
  src/db/models/authTarget.ts
  src/db/util/conditions.ts
  src/db/util/id-model.ts
  src/db/util/raw-model.ts
  src/db/util/validation.ts
  src/db/util/versioned-model.ts
  tests/testContext.ts
  tests/utils/connection.ts
  yarn.lock
Labels: ready for review, dependencies
