Repository UN-OCHA/hpc-api-core, pull requests merged in 2025-01, with the labels that each got.

#209 Update `@unocha/hpc-repo-tools` to `v5.5.0`
  package.json
  yarn.lock
Labels: ready for merge, dependencies

#202 HPC-9997: Simplify `support` array in `PLAN_ENTITY_VERSION_VALUE` codec
  package.json
  src/db/models/planEntityVersion.ts
Labels: ready for merge, pending prior merge

#211 HPC-10005: Plan visibility for new projects
  package.json
  src/db/models/planVersion.ts
Labels: ready for merge

#213 Simplify code after cleaning up `support` array of `planEntityVersion` codec
  package.json
  src/lib/data/planEntities.ts
Labels: ready for merge

#210 HPC-9824: Coordinating organization information gets deleted from plan details
  package.json
  src/auth/permissions.ts
  src/auth/roles.ts
Labels: ready for merge
